#!/bin/bash
# Needs the LispBM repl built 64-bit and on PATH as lbm:
#   cd vesc_express/main/lispBM/repl && make FEATURES="64" && cp repl ~/.local/bin/lbm
lbm -H 400000 -M 4000000 -s make_fonts.lbm --terminate
