; Copyright 2026 Stephen Bouche
; SPDX-License-Identifier: GPL-3.0-or-later
; The fade only shows while a region is held, which a golden render cannot
; reach. Drive it directly at several hold fractions.
(import "stubs.lisp" 'code-stubs)
(read-eval-program code-stubs)
(def splash-version "test")
(def C "build/common/")
(def B "build/s3/")
(import (str-merge B "config.lisp") 'c-config)
(import (str-merge C "lib/vehicle-state.lisp") 'c-vehicle)
(import (str-merge C "lib/colors.lisp") 'c-colors)
(import (str-merge C "lib/user-settings.lisp") 'c-user)
(import (str-merge C "lib/persistent-settings.lisp") 'c-persist)
(import (str-merge C "lib/statistics.lisp") 'c-stats)
(import (str-merge C "lib/draw-utils.lisp") 'c-draw)
(import (str-merge C "lib/battery.lisp") 'c-batt)
(import (str-merge B "lib/input.lisp") 'c-input)
(import (str-merge C "views/view_static.lbm") 'c-static)
(import (str-merge C "views/view_pages.lbm") 'c-pages)
(read-eval-program c-config) (read-eval-program c-vehicle)
(read-eval-program c-colors) (read-eval-program c-user)
(read-eval-program c-persist) (read-eval-program c-stats)
(read-eval-program c-draw) (read-eval-program c-batt)
(read-eval-program c-input) (read-eval-program c-static)
(read-eval-program c-pages)
(import (str-merge B "font/roboto-bold-108-4c.bin") 'font-speed)
(import (str-merge B "font/roboto-bold-40-4c.bin") 'font-40)
(import (str-merge B "font/roboto-bold-24-4c.bin") 'font-24)
(import (str-merge B "font/roboto-bold-16-4c.bin") 'font-16)
(def dm-pool (dm-create config-dm-pool))
(def screen (img-buffer 'rgb888 disp-w disp-h))
(set-active-img screen) (display-to-img)
(settings-load) (settings-build) (colors-build) (settings-apply-units)
(def stats-kmh-max 58.0) (def stats-kw-max 6.1) (def stats-amps-now-max 88.0)
(def stats-temp-esc-max 52.0) (def stats-temp-motor-max 71.0)
(def stats-temp-battery-max 31.0) (def stats-duty 0.37)

(print (list 'reset-region-bound-to (session-reset-region)))

(looprange n 0 5 {
        (var f (/ (to-float n) 4.0))
        (setq btn-hold-region (session-reset-region))
        (setq btn-hold-progress f)
        (disp-clear 0)
        (page-session true)
        (page-session nil)
        (save-active-img (str-merge "out/fade_" (str-from-n n "%d") ".png"))
})
; Releasing must restore it
(setq btn-hold-region nil)
(setq btn-hold-progress 0.0)
(disp-clear 0)
(page-session true)
(page-session nil)
(save-active-img "out/fade_released.png")
(print 'done)
